import Modules from "@/pages/Modules/Modules";

export default function AiModuleLog() {
  return (
    <div className="p-4">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">AI Module Log</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Review and manage LMS modules generated by Lumi.
          </p>
        </div>
      </div>

      <Modules itemsPerPage={8} isAiOnly={true} />
    </div>
  );
}
